# docker-compose.base.yml - Base with all Docker containers except the Joomla web servers.
#
# MIT License, Copyright (c) 2024 Heiko Lübbe
# https://github.com/muhme/joomla-branches-tester

services:

  mysql:
    container_name: jbt_mysql
    # Joomla 5 needs >= 8.0.13, actual 8.1.0
    # and hardwire as 8.1 as 8.4 needs mysql_native_password=ON
    restart: unless-stopped
    image: mysql:8.1
    ports:
      - "7011:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  mariadb:
    container_name: jbt_madb
    restart: unless-stopped
    image: mariadb:10.4
    ports:
      - "7012:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  postgres:
    container_name: jbt_pg
    restart: unless-stopped
    image: postgres:12
    ports:
      - "7013:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  myadmin:
    container_name: jbt_mya
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: jbt_mysql:3306, jbt_madb:3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7001:80"
    restart: unless-stopped
    depends_on:
      - mysql
      - postgres

  pgadmin:
    container_name: jbt_pga
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # https://stackoverflow.com/questions/70883515/pgadmin-disable-login-dialog-automatic-login
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "7002:80"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      # Make a server entry for 'jbt_pg'
      - ./scripts/servers.json:/pgadmin4/servers.json
      - ./scripts/pgpass:/pgadmin4/pgpass
      # pgpass file must me only owner read & writable
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh"

  cypress:
    container_name: jbt_cypress
    image: cypress/included # actual (August 2024) versions are Cypress 13.7, Electon 114, Chrome 116, Edge 116 and Firefox 117
    environment:
      DISPLAY:  
    restart: unless-stopped
    entrypoint: ["sleep", "31536000"] # don't use cypress run, instead sleep one year
    ports:
      - 7125:7125 # smtp-tester port (only available during the test run)
    volumes:
      - ./branch_44:/branch_44
      - ./branch_51:/branch_51
      - ./branch_52:/branch_52
      - ./branch_60:/branch_60
      - ./scripts:/scripts
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    extra_hosts:
      - "host.docker.internal:host-gateway"

  relay:
    container_name: jbt_relay
    image: smtp-double-relay
    build:
      context: .
      dockerfile: dockerfile-relay.yml
    environment:
      LISTEN_PORT: 7025
      TARGET_HOST1: host.docker.internal
      TARGET_PORT1: 7125
      TARGET_HOST2: host.docker.internal
      TARGET_PORT2: 7225
    depends_on:
      - mail
      - cypress
    ports:
      - "7025:7025"

  mail:
    container_name: jbt_mail
    image: maildev/maildev
    ports:
      - "7003:1080"
      - "7225:1025"
