# docker-compose.base.yml - Base with all Docker containers except the Joomla web servers.
#
# Distributed under the GNU General Public License version 2 or later, Copyright (c) 2024 Heiko Lübbe
# https://github.com/muhme/joomla-branches-tester

# IPv4 (default):
# - subnet 192.168.150.0/24
# - enable_ipv6: false
# IPv6 (scripts/create IPv6):
# - subnet 2003:c2:6727:cb00::/64
# - enable_ipv6: true
#
networks:
  jbt_network:
    name: jbt_network
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: "192.168.150.0/24"

services:

  mysql:
    container_name: jbt_mysql
    # Joomla 5 needs >= 8.0.13, actual 8.1.0
    # and hardwire as 8.1 as 8.4 needs mysql_native_password=ON
    restart: unless-stopped
    image: mysql:8.1
    ports:
      - "7011:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mysql-socket:/var/run/msysqld
    networks:
      - jbt_network

  mariadb:
    container_name: jbt_madb
    restart: unless-stopped
    image: mariadb:10.4
    ports:
      - "7012:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mariadb-socket:/var/run/msysqld
    networks:
      - jbt_network

  postgres:
    container_name: jbt_pg
    restart: unless-stopped
    # Not using version 16, as waiting for https://github.com/joomla-framework/database/pull/295
    # with ERROR: unrecognized configuration parameter "lc_collate"
    image: postgres:15
    ports:
      - "7013:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - postgresql-socket:/var/run/postgresql
    networks:
      - jbt_network

  myadmin:
    container_name: jbt_mya
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: jbt_mysql:3306, jbt_madb:3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7001:80"
    restart: unless-stopped
    depends_on:
      - mysql
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jbt_network

  pgadmin:
    container_name: jbt_pga
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # https://stackoverflow.com/questions/70883515/pgadmin-disable-login-dialog-automatic-login
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "7002:80"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      # Make a server entry for 'jbt_pg'
      - ./scripts/servers.json:/pgadmin4/servers.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jbt_network

  cypress:
    container_name: jbt_cypress
    image: cypress/included # actual (August 2024) versions are Cypress 13.7, Electron 114, Chrome 116, Edge 116 and Firefox 117
    restart: unless-stopped
    entrypoint: ["sleep", "31536000"] # don't use cypress run, instead sleep one year
    ports:
      - 7125:7125 # smtp-tester port (only available during the test run)
    volumes:
      - .:/jbt
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cypress-cache:/root/.cache/Cypress # Cypress and web server containers
      - mysql-socket:/var/run/mysql-socket
      - mariadb-socket:/var/run/mariadb-socket
      - postgresql-socket:/var/run/postgresql-socket
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jbt_network
    depends_on:
      - novnc
      - mysql
      - mariadb
      - postgres

  novnc:
    container_name: jbt_novnc
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
      - RUN_XTERM=no
    restart: unless-stopped
    ports:
      - "7900:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jbt_network

  relay:
    container_name: jbt_relay
    build:
      context: .
      dockerfile: dockerfile-relay.yml
    environment:
      LISTEN_PORT: 7025
      TARGET_HOST_1: host.docker.internal
      TARGET_PORT_1: 7125
      TARGET_HOST_2: host.docker.internal
      TARGET_PORT_2: 7225
      TARGET_HOST_3: host.docker.internal
      TARGET_PORT_3: 7325
    restart: unless-stopped
    depends_on:
      - mail
      - cypress
    ports:
      - "7025:7025"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jbt_network

  mail:
    container_name: jbt_mail
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - "7003:1080"
      - "7225:1025"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jbt_network
